
List<string> words = new List<string> { earthquake, undress, alive, comfortable, precious, orange, person, gabby, average, consist, spot, race, fuzzy, root, part, story, realize, cure, squalid, married, balance, cabbage, great, unwieldy, air, guide, spray, broken, shrug, match, relation, pathetic, bee, advice, holistic, adaptable, shame, fireman, visit, cub, attend, harmony, look, notebook, stingy, unique, tawdry, memorize, agreement, disagreeable, luxuriant, wrong, fearless, reply, ultra, ghost, knife, lake, route, verdant, stupid, peace, wind, rightful, surround, four, manage, hover, dreary, tart, bake, good, tight, file, writing, tank, womanly, scrape, sincere, elfin, brother, grandfather, satisfying, reward, second, join, society, fang, scary, sore, decide, bruise, muddled, texture, material, playground, skirt, determined, bird, condemned, vengeful, wheel, tiger, choke, sniff, lewd, record, fat, zipper, stew, malicious, quirky, descriptive, stranger, grotesque, resonant, meaty, fluffy, achiever, first, domineering, care, crooked, mysterious, exultant, chickens, trite, rare, cup, overt, stem, fill, ashamed, eggs, numberless, arithmetic, premium, grumpy, ancient, fragile, addicted, thought, yielding, place, belong, rings, beneficial, boiling, expert, cough, ducks, existence, blind, tremble, mute, heavenly, ants, soup, prefer, dock, resolute, face, wound, help, gigantic, pleasure, seemly, bore, interest, acid, aftermath, flame, handsomely, second - hand, earth, argument, explode, suggest, quaint, toes, sulky, mass, argue, pump, babies, honey, disarm, tomatoes, trick, spiffy, typical, station, seashore, hushed, cave, education, add, unfasten, bleach, tomato };

List<int> wordsnumber = new List<int> { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };


Random rnd = new Random();

for (int i = 0; i <= 199; i++)
    int random = rnd.Next(0, 199)